### ISSUE TITLE
Can't use CSS files with react

### ISSUE THREAD

**Issue by MarcoPortillo** [liferay/liferay-js-toolkit#433] opened 2019-10-04 18:12 UTC
Hi guys,

I am developing a portlet with liferay, I am using React, I followed the steps indicate here: https://portal.liferay.dev/docs/7-2/appdev/-/knowledge_base/a/developing-a-react-application the portlet is working just fine until I try to import CSS files, I come from the liferay 7.1 and I am updating to 7.2, in my previous version I have a couple of react libraries which need to import CSS files in order to work, for example https://github.com/v0ltoz/react-datetimepicker almost of the files within the library is importing a CSS file, which is part also of the library.

I understand that if I have personal CSS files, I just need to import all of them in /css/styles.css, this work just fine but this css file which is part of the react-datetimepicker proyect, and not the portlet itself, and I really need this to work, I already installed the css-loader and style-loader, I also configure my webpack.config.js, I also tried using this https://github.com/liferay/liferay-js-toolkit/wiki/List-of-loaders it didn't work either. What should I do?

This is the error:

```
 · Error cause: Error: The following problems where detected while resolving modules:
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/DateTimeRangeContainer'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/DateTimeRangePicker'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/ranges/Ranges'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/ranges/RangeButton'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/date_picker/DatePicker'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/date_picker/Label'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/date_picker/DateField'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/date_picker/TimeField'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/calendar/Calendar'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/calendar/MonthYearSelector'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/calendar/CalendarHeader'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/calendar/CalendarRows'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/calendar/CalendarRow'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/calendar/Cell'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/date_picker/ApplyCancelButtons'
    · Missing dependency 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/style/DateTimeRange.css' of 'infoserver-react$react-advanced-datetimerange-picker@1.0.8/dist/date_picker/ActiveNotifier'
```

Any ideas? I cannot use any library with styles.

**Comment by izaera** [comment] 2019-10-10 07:44
OK @MarcoPortillo . Read my comments in the other two issues and we can settle on this to follow :-D

**Comment by MarcoPortillo** [comment] 2019-10-11 22:15
@izaera Thanks for your help, still not luck, I installed all the loaders and I did as you did in your examples, still says Missing dependency. 

I also tried using create-react-app and with the adapter, it works but now I cannot use the Liferay variable when I am going to deploy to Liferay server, it compiles the app as a normal react app and throws an error saying Liferay is undefined, I have a lot of APIs calls with Liferay.Service, and is the way I need to use it :/, I am geting crazy

**Comment by izaera** [comment] 2019-10-14 07:18
Can you send a ZIP with your project? Or at least the package.json, .npmbundlerrc and the liferay-npm-bundler-report.html file?

**Comment by izaera** [comment] 2019-12-20 12:46
This looks like a duplicate of #459

**Closed by izaera** 2019-12-20 12:46 UTC
