### ISSUE TITLE
liferay-npm-scripts doesnt translate react-datetime correctly

### ISSUE THREAD

**Issue by rahulahoop** [liferay/liferay-js-toolkit#593] opened 2020-06-03 14:13 UTC
react-datepicker has a dependency to object-is.

Object-is's index file is like this (before translation)

```
'use strict';

var define = require('define-properties');
var callBind = require('es-abstract/helpers/callBind');

var implementation = require('./implementation');
var getPolyfill = require('./polyfill');
var shim = require('./shim');

var polyfill = callBind(getPolyfill(), Object);

define(polyfill, {
	getPolyfill: getPolyfill,
	implementation: implementation,
	shim: shim
});

module.exports = polyfill;
```

This causes issue in browser "defined is not defined" because liferay-npm-scripts fails to convert this class and add the Liferay.Loader.define() to the translated file; assumedly because there is already a define fnc/method here.
In browser, it is translated like this;

![image](https://user-images.githubusercontent.com/7705259/83647377-1ba9d500-a5b5-11ea-9cf9-7715370f27d1.png)

As you can see there is no Liferay.Loader.define, but only a define.

This prevents react-datepicker from being used in liferay, and in turn any lib using a method with define()

I am using: 
"liferay-npm-scripts": "32.2.0"

**Comment by wincent** [comment] 2020-06-03 14:20
Originally posted [here](https://github.com/liferay/liferay-npm-tools/issues/461) but I redirected over here because it seemed more of a bundler issue based on an initial glance. @izaera, please correct me if I'm wrong about that.

**Comment by izaera** [comment] 2020-06-04 06:56
In fact, this is a duplicate of #589

**Closed by izaera** 2020-06-04 06:56 UTC
