### ISSUE TITLE
Json Loader is not creating the json.js files I expect

### ISSUE THREAD

**Issue by rahulahoop** [liferay/liferay-js-toolkit#500] opened 2020-02-03 14:35 UTC
Hi I want json loader to run on my json files so that I can import them as a resource for things like i18n.

for example 
```	
const enJson = require("./i18n/en.json");
const deJson = require("./i18n/de.json");

const resources = {
	en: {
		translation: enJson
	},
	de: {
		translation: deJson

	}
};
```	

```	
"devDependencies": {
		"babel-cli": "6.26.0",
		"babel-loader": "7.1.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "1.7.0",
		"babel-preset-react": "6.24.1",
		"copy-webpack-plugin": "4.6.0",
		"i18next-browser-languagedetector": "^4.0.1",
		"i18next-xhr-backend": "^3.2.2",
		"liferay-font-awesome": "3.4.0",
		"liferay-npm-build-support": "^2.17.0",
		"liferay-npm-bundler": "^2.17.0",
		"liferay-npm-bundler-loader-babel-loader": "^2.17.1",
		"liferay-npm-bundler-loader-json-loader": "^2.17.1",
		"liferay-npm-bundler-loader-sass-loader": "^2.17.1",
		"node-sass": "^4.13.1",
		"webpack": "4.29.6",
		"webpack-cli": "3.3.0",
		"webpack-dev-server": "3.2.1"
	},
	"dependencies": {
		"react-datetime": "^2.16.3",
		"redux": "^4.0.5",
		"react-redux": "^7.1.3",
		"react-i18next": "^11.3.1",
		"redux-thunk": "^2.3.0",
		"react": "16.8.6",
		"react-dom": "16.8.6",
		"react-router-dom": "^5.1.2",
		"moment": "^2.24.0",
		"i18next": "^19.0.3",
		"i18next-xhr-backend": "^3.2.2",
		"typescript": "^3.7.4"
	},
	"scripts": {
		"build": "node-sass src/css/ -o assets/css/ && babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"translate": "lnbs-translate",
		"deploy": "npm run build && lnbs-deploy",
		"start": "lnbs-start"
	},
```

Here is my npmbundlerrc:

```
{
	"create-jar": {
		"output-dir": "dist",
		"features": {
			"js-extender": true,
			"web-context": "/importlet",
			"localization": "features/localization/Language",
			"configuration": "features/configuration.json"
		}
	},
	"dump-report": true,
	"verbose": true,
	"rules": [
    	{
    		"test": "css\\/*\\.scss$",
    		"exclude": "node_modules",
    		"use": ["sass-loader"]
    	},
    	{
    	    "test": "i18n\\/*\\.json$",
    	    "use": ["json-loader"]
    	}
    ]
}
```

and this is where my assumption comes from in the index.js of json-loader:
```
	try {
		content = JSON.stringify(JSON.parse(content));

		// content = content.replace(//g, '\n');

		context.extraArtifacts[`${filePath}.js`] = `
module.exports = JSON.parse(${JSON.stringify(content)});
`;
	}
```

when I run npm run build/deploy i expect the json files to turn into json.js files in my build folder but nothing of the sort happens.

When i run with "npm run start" this works because require(JSON) is supported in webpack.
Im not sure how to resolve a osgi url ("o/portlet/my.json") and then store the contents in a variable in react and i dont want to make a self-fetch call 

lastly this is the error im getting in browser:

```

Missing dependency 'importlet@1.0.0/i18n/en.json' of 'importlet@1.0.0/i18n'
Missing dependency 'importlet@1.0.0/i18n/de.json' of 'importlet@1.0.0/i18n'
```

What are my options ?

**Comment by izaera** [comment] 2020-02-05 09:26
I think the problem is in your `rules`, because your regexps are incorrect:

```
i18n\\/*\\.json$
```
only matches `i18n/.json` and `i18n.json`

You are missing a `.` before the `*`.

Also you are missing a [sources](https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-reference#sources) entry. Otherwise rules won't be applied to anything (see this [wiki page](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-liferay-npm-bundler#how-rules-run))

To finish with, rules are relative to the project folder, so if you have `src` and `i18n` folders, you must set `sources` to `["src", "i18n"]` and then that part is stripped from the module name, so you don't `require("./i18n/en.json")` but `require("./en.json")`. However I'm not 100% sure of this (talking off the top of my head), so please check it.

**Comment by izaera** [comment] 2020-02-05 09:27
I'm closing this. If you have more doubts related to this feel free to reopen.

**Closed by izaera** 2020-02-05 09:27 UTC
Labels: question
