### ISSUE TITLE
Liferay npm React portlet - problem using npm libraries 

### ISSUE THREAD

**Issue by bosna387** [liferay/liferay-js-toolkit#350] opened 2019-06-13 11:39 UTC
Hi All,

I have a problem thats bugging my head for awhile now. I want to use React in portlets but it seems insanely hard. Without adding libraries such as react-bootstrap-table portlet loads fine.
As soon as I want to use npm libraries such as react-bootstrap-table or datatables.net (i guess libraries that use jquery) I get missing constraints problems. Browser console error is:
Missing version constraints for react-npm-portlet$events in package.json of react-npm-portlet$react-bootstrap-table@4.3.1"
    jQuery 2
        _getResolutionError
        require
And I get blank portlet. No table shown. Importing other npm libraries such as moment etc work fine. It is only these table related libraries that don't compile well.
I have tried other npm libraries but same errors. What am I doing wrong. How do I import and use npm libraries that do tables into liferay.
I am using blade sample liferay npm react (https://github.com/liferay/liferay-blade-samples/tree/7.1/gradle/apps/npm/react-npm-portlet) here is my index.es.js (i have only changed index.es.js and package.json in the sample)
`import` React from 'react';
`import ReactDOM from 'react-dom';
`import {BootstrapTable, TableHeaderColumn} from  'react-bootstrap-table';
`var products = [{
`    id: 1,
`    name: "Product1",
`    price: 120
`}, {
`    id: 2,
`    name: "Product2",
`    price: 80
`}];
`export default function(elementId) {
`    ReactDOM.render(<BootstrapTable data={products} striped hover>
`    <TableHeaderColumn isKey dataField='id'>Product ID</TableHeaderColumn>
`    <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
`    <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>``
`</BootstrapTable>, document.getElementById(elementId));
`}

Package.json
{
    "dependencies": {
        "react": "15.6.2",
        "react-bootstrap-table": "^4.3.1",
        "react-dom": "15.6.2"
    },
    "description": "React Portlet",
    "devDependencies": {
        "babel-cli": "^6.26.0",
        "babel-preset-env": "^1.7.0",
        "babel-preset-react": "6.24.1",
        "liferay-npm-bundler": "^2.0.0"
    },
    "main": "lib/index.es.js",
    "name": "react-npm-portlet",
    "private": true,
    "scripts": {
        "build": "babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources && liferay-npm-bundler"
    },
    "version": "1.0.0"
}

All i did was in the root folder npm i react-bootstrap-table to install the library. Is there additional step that I am missing?

Appreciate your help.

**Comment by MVTalent** [comment] 2019-06-14 03:52
I have the same problem. Installed liferay-ce-portal-7.2.0-ga1. I want to use npm libraries such "react-jsonschema-form" or "react-select". After deployment, I get an "empty" portlet. There are no errors in the console of the browser, in logs Liferay too empty

package.json

> {
	"dependencies": {
		"@babel/plugin-proposal-class-properties": "^7.4.4",
		"@babel/plugin-proposal-decorators": "^7.4.4",
		"axios": "^0.18.0",
		"create-react-class": "^15.6.3",
		"mobx": "^5.10.1",
		"mobx-react": "^6.0.3",
		"prop-types": "^15.7.2",
		"react": "^16.8.6",
		"react-dom": "16.8.6",
		"react-jsonschema-form": "^1.6.1",
		"react-redux": "^7.1.0",
		"react-router-dom": "^5.0.0",
		"redux": "^4.0.1",
		"redux-thunk": "^2.3.0"
	},
	"devDependencies": {
		"babel-cli": "^6.26.0",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.7.0",
		"babel-preset-react": "6.24.1",
		"liferay-npm-bundler": "^2.10.0"
	},
	"main": "lib/index.es.js",
	"name": "zskp-web",
	"scripts": {
		"build": "babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources && liferay-npm-bundler"
	},
	"version": "1.0.0"
}

.babelrc

> {
	"presets": ["env", "react"],
	"plugins": [
		"transform-decorators-legacy",
		"transform-class-properties",
		"transform-object-rest-spread"
	]
}

**Comment by izaera** [comment] 2019-06-20 07:22
@MVTalent please follow the steps in https://github.com/liferay/liferay-js-toolkit/wiki/How-to-troubleshoot-your-setups to see something in the console. Thx.

**Comment by MVTalent** [comment] 2019-06-25 18:05
After https://github.com/liferay/liferay-js-toolkit/wiki/How-to-troubleshoot-your-setups I get an error in the web browser console
[problem_using_npm.log](https://github.com/liferay/liferay-js-toolkit/files/3326686/problem_using_npm.log)

**Comment by phillipsheridan** [comment] 2019-06-26 18:25
I am also having trouble using some npm packages. Note I am using a pure js project generated using the yeoman liferay-js react generator.

 Importing from scoped packages such as

`import Button from '@material-ui/core/Button';`

is giving the following error:

`The resource from “http://localhost:8085/o/js/resolved-module/@6-26-921$material-ui/core@4.0.0-rc.0/.js?languageId=en_US” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

While  `import now from 'lodash';` works fine

Looking in the debugger I don't see the package in resolved-dependencies folder:

![liferay-npm-1](https://user-images.githubusercontent.com/11233791/60204312-8dfa2d00-981c-11e9-9738-d1c745097ebe.PNG)
![liferay-npm-2](https://user-images.githubusercontent.com/11233791/60204313-8dfa2d00-981c-11e9-97bd-ffa651d6d80d.PNG)

If I import the button like `import { Button } from '@material-ui/core';` then I can see the package in the resolved-dependencies folder, but it doesn't match the path that the browser needs because it is appending .js without the index:

```
The resource from “http://localhost:8085/o/js/resolved-module/@6-26-921$material-ui/core@4.0.0-rc.0/.js?languageId=en_US” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost:8085
Liferay AMD Loader: Unhandled failure: 
<script src="http://localhost:8085/o/…c.0/.js?languageId=en_US">
 while resolving modules: 
Array [ "6-26-921@1.0.0/index" ]
```
![liferay-npm-3](https://user-images.githubusercontent.com/11233791/60204847-bc2c3c80-981d-11e9-8c60-b594de1c9223.PNG)

**Comment by izaera** [comment] 2019-07-16 10:32
@phillipsheridan what is `6-26-921`? The name of your project? 

Apparently it is fooling someone into thinking that it is an npm scope (I infer that because the failing requests contain `@6-26-921`)...

**Comment by phillipsheridan** [comment] 2019-07-16 11:02
Yeah it's the name of the project.

**Comment by izaera** [comment] 2019-07-17 10:53
@bosna387 @MVTalent @phillipsheridan  First of all, you don't have all the same problem ;-).

Also, make sure to follow https://github.com/liferay/liferay-js-toolkit/wiki/How-to-troubleshoot-your-setups before reporting any issue. Otherwise, the information you will see will be very poor and we won't be able to know what is happening either.

@bosna387 AFAIK, react tables have circular deps, so you are being hit by https://github.com/liferay/liferay-amd-loader/issues/182. Correct me if I'm wrong.

@MVTalent Yours is a duplicate of #303 (in this case because some of you modules, specifically the JSON schema validator you are using, is requesting .json files)

@phillipsheridan Can you provide the source code of the project or, at least, the producer JAR file? Thx. I'm closing this issue now. Feel free to create a new one when providing the requested information.

Cheers,
Ivan

**Closed by izaera** 2019-07-17 10:53 UTC
Labels: question
