### ISSUE TITLE
Load the index.js in packages as default

### ISSUE THREAD

**Issue by ibhlool7** [liferay/liferay-js-toolkit#377] opened 2019-08-07 04:26 UTC
Hello
I've tried to import a package that contains an `index.js` as like as the Webpack but my dependency (exactly my index.js) didn't find and I got an error in my browser console
my package structure:

![ted](https://user-images.githubusercontent.com/29673016/62594295-54264700-b8ef-11e9-99de-78442862f7cf.PNG)

this is my index.js code :
```
import TextField from "./components/TextField";
import TextareaField from "./components/TextareaField";
import SelectField from "./components/SelectField";

export {
  TextField,

  SelectField,
  TextareaField
};

```
I'm tried to import these components to `HelpPops.js` as follow :
`import {TextareaField} from "./Fields"`

I have a question :
   I want to contribute to this project, where can I implement this logic in this project?

**Comment by izaera** [comment] 2019-08-07 08:30
This is a duplicate of #324, so I'm closing it as duplicate.

Regarding the fix, it's not easy if we want to do it in a sustainable way because it has more implications, as we are coming from a background where the loader was of type AMD and thus it doesn't know what `index.js` means. So I would advise just putting `index` in the import, for now. 

Something like:

`import {TextAreaField}  from "./Fields/index"`

**Closed by izaera** 2019-08-07 08:30 UTC
Labels: duplicate
